### ISSUE TITLE
SternalBoard console WARNS

### ISSUE THREAD

**Issue by FixYourWork** [ShieldCommunity/SternalBoard#47]
Sometimes when player left sometimes when player is join sometimes when player is online
This is appears in console too much.

[22:57:14] [WARN]: Exception in thread "Craft Scheduler Thread - 13" Exception in thread "Craft Scheduler Thread - 25" org.apache.commons.lang.UnhandledException: Plugin SternalBoard v2.1.0 generated an exception while executing task 52
[22:57:14] [WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(SourceFile:57)
[22:57:14] [WARN]: 	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(SourceFile:22)
[22:57:14] [WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[22:57:14] [WARN]: 	at java.util.concurrent.ThreadP
[12312.txt](https://github.com/ShieldCommunity/SternalBoard/files/11193569/12312.txt)
oolExecutor$Worker.run(Unknown Source)
[22:57:14] [WARN]: 	at java.lang.Thread.run(Unknown Source)
[22:57:14] [WARN]: Caused by: java.lang.RuntimeException: Unable to update SternalBoard lines
[22:57:14] [WARN]: 	at com.xism4.sternalboard.SternalBoardHandler.updateLine(SternalBoardHandler.java:272)
[22:57:14] [WARN]: 	at com.xism4.sternalboard.managers.animation.tasks.LineUpdateTask.run(LineUpdateTask.java:38)
[22:57:14] [WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(SourceFile:59)
[22:57:14] [WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(SourceFile:53)
[22:57:14] [WARN]: 	... 4 more
[22:57:14] [WARN]: Caused by: java.lang.IllegalStateException: This SternalBoard is deleted
[22:57:14] [WARN]: 	at com.xism4.sternalboard.SternalBoardHandler.sendPacket(SternalBoardHandler.java:566)
[22:57:14] [WARN]: 	at com.xism4.sternalboard.SternalBoardHandler.sendTeamPacket(SternalBoardHandler.java:561)
[22:57:14] [WARN]: 	at com.xism4.sternalboard.SternalBoardHandler.updateLine(SternalBoardHandler.java:256)
[22:57:14] [WARN]: 	... 7 more
[22:57:14] [WARN]: org.apache.commons.lang.UnhandledException: Plugin SternalBoard v2.1.0 generated an exception while executing task 53
[22:57:14] [WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(SourceFile:57)
[22:57:14] [WARN]: 	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(SourceFile:22)
[22:57:14] [WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[22:57:14] [WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[22:57:14] [WARN]: 	at java.lang.Thread.run(Unknown Source)
[22:57:14] [WARN]: Caused by: java.lang.RuntimeException: Unable to update SternalBoard lines
[22:57:14] [WARN]: 	at com.xism4.sternalboard.SternalBoardHandler.updateLine(SternalBoardHandler.java:272)
[22:57:14] [WARN]: 	at com.xism4.sternalboard.managers.animation.tasks.LineUpdateTask.run(LineUpdateTask.java:38)
[22:57:14] [WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(SourceFile:59)
[22:57:14] [WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(SourceFile:53)
[22:57:14] [WARN]: 	... 4 more
[22:57:14] [WARN]: Caused by: java.lang.IllegalStateException: This SternalBoard is deleted
[22:57:14] [WARN]: 	at com.xism4.sternalboard.SternalBoardHandler.sendPacket(SternalBoardHandler.java:566)
[22:57:14] [WARN]: 	at com.xism4.sternalboard.SternalBoardHandler.sendTeamPacket(SternalBoardHandler.java:561)
[22:57:14] [WARN]: 	at com.xism4.sternalboard.SternalBoardHandler.updateLine(SternalBoardHandler.java:256)
[22:57:14] [WARN]: 	... 7 more

**Comment by jonakls** [comment]
Hi @FixYourWork, could you let me see your configuration file?

**Comment by FixYourWork** [comment]
The problem is not about config because i have tried with default config either doesnt change anything.
It is more often appears when someone is kicking, quit.

**Comment by xIsm4** [comment]
> Sometimes when player left sometimes when player is join sometimes when player is online This is appears in console too much.
> 
> [22:57:14] [WARN]: Exception in thread "Craft Scheduler Thread - 13" Exception in thread "Craft Scheduler Thread - 25" org.apache.commons.lang.UnhandledException: Plugin SternalBoard v2.1.0 generated an exception while executing task 52 [22:57:14] [WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(SourceFile:57) [22:57:14] [WARN]: at org.github.paperspigot.ServerSchedulerReportingWrapper.run(SourceFile:22) [22:57:14] [WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [22:57:14] [WARN]: at java.util.concurrent.ThreadP [12312.txt](https://github.com/ShieldCommunity/SternalBoard/files/11193569/12312.txt) oolExecutor$Worker.run(Unknown Source) [22:57:14] [WARN]: at java.lang.Thread.run(Unknown Source) [22:57:14] [WARN]: Caused by: java.lang.RuntimeException: Unable to update SternalBoard lines [22:57:14] [WARN]: at com.xism4.sternalboard.SternalBoardHandler.updateLine(SternalBoardHandler.java:272) [22:57:14] [WARN]: at com.xism4.sternalboard.managers.animation.tasks.LineUpdateTask.run(LineUpdateTask.java:38) [22:57:14] [WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(SourceFile:59) [22:57:14] [WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(SourceFile:53) [22:57:14] [WARN]: ... 4 more [22:57:14] [WARN]: Caused by: java.lang.IllegalStateException: This SternalBoard is deleted [22:57:14] [WARN]: at com.xism4.sternalboard.SternalBoardHandler.sendPacket(SternalBoardHandler.java:566) [22:57:14] [WARN]: at com.xism4.sternalboard.SternalBoardHandler.sendTeamPacket(SternalBoardHandler.java:561) [22:57:14] [WARN]: at com.xism4.sternalboard.SternalBoardHandler.updateLine(SternalBoardHandler.java:256) [22:57:14] [WARN]: ... 7 more [22:57:14] [WARN]: org.apache.commons.lang.UnhandledException: Plugin SternalBoard v2.1.0 generated an exception while executing task 53 [22:57:14] [WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(SourceFile:57) [22:57:14] [WARN]: at org.github.paperspigot.ServerSchedulerReportingWrapper.run(SourceFile:22) [22:57:14] [WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [22:57:14] [WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [22:57:14] [WARN]: at java.lang.Thread.run(Unknown Source) [22:57:14] [WARN]: Caused by: java.lang.RuntimeException: Unable to update SternalBoard lines [22:57:14] [WARN]: at com.xism4.sternalboard.SternalBoardHandler.updateLine(SternalBoardHandler.java:272) [22:57:14] [WARN]: at com.xism4.sternalboard.managers.animation.tasks.LineUpdateTask.run(LineUpdateTask.java:38) [22:57:14] [WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(SourceFile:59) [22:57:14] [WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(SourceFile:53) [22:57:14] [WARN]: ... 4 more [22:57:14] [WARN]: Caused by: java.lang.IllegalStateException: This SternalBoard is deleted [22:57:14] [WARN]: at com.xism4.sternalboard.SternalBoardHandler.sendPacket(SternalBoardHandler.java:566) [22:57:14] [WARN]: at com.xism4.sternalboard.SternalBoardHandler.sendTeamPacket(SternalBoardHandler.java:561) [22:57:14] [WARN]: at com.xism4.sternalboard.SternalBoardHandler.updateLine(SternalBoardHandler.java:256) [22:57:14] [WARN]: ... 7 more

Seems some task is having issues when updating the scoreboard lines.

**Comment by FixYourWork** [comment]
Latest version 2.2.0 has same issue also it seems animated section doesnt work. You have to reload after restart in order to apply animated settings you have use /sternalboard reload command.

**Comment by xIsm4** [comment]
> Latest version 2.2.0 has same issue also it seems animated section doesnt work. You have to reload after restart in order to apply animated settings you have use /sternalboard reload command.

It works for me, i cant replicate this.

**Comment by xism4** [comment]
> Sometimes when player left sometimes when player is join sometimes when player is online This is appears in console too much.
> 
> [22:57:14] [WARN]: Exception in thread "Craft Scheduler Thread - 13" Exception in thread "Craft Scheduler Thread - 25" org.apache.commons.lang.UnhandledException: Plugin SternalBoard v2.1.0 generated an exception while executing task 52 [22:57:14] [WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(SourceFile:57) [22:57:14] [WARN]: at org.github.paperspigot.ServerSchedulerReportingWrapper.run(SourceFile:22) [22:57:14] [WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [22:57:14] [WARN]: at java.util.concurrent.ThreadP [12312.txt](https://github.com/ShieldCommunity/SternalBoard/files/11193569/12312.txt) oolExecutor$Worker.run(Unknown Source) [22:57:14] [WARN]: at java.lang.Thread.run(Unknown Source) [22:57:14] [WARN]: Caused by: java.lang.RuntimeException: Unable to update SternalBoard lines [22:57:14] [WARN]: at com.xism4.sternalboard.SternalBoardHandler.updateLine(SternalBoardHandler.java:272) [22:57:14] [WARN]: at com.xism4.sternalboard.managers.animation.tasks.LineUpdateTask.run(LineUpdateTask.java:38) [22:57:14] [WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(SourceFile:59) [22:57:14] [WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(SourceFile:53) [22:57:14] [WARN]: ... 4 more [22:57:14] [WARN]: Caused by: java.lang.IllegalStateException: This SternalBoard is deleted [22:57:14] [WARN]: at com.xism4.sternalboard.SternalBoardHandler.sendPacket(SternalBoardHandler.java:566) [22:57:14] [WARN]: at com.xism4.sternalboard.SternalBoardHandler.sendTeamPacket(SternalBoardHandler.java:561) [22:57:14] [WARN]: at com.xism4.sternalboard.SternalBoardHandler.updateLine(SternalBoardHandler.java:256) [22:57:14] [WARN]: ... 7 more [22:57:14] [WARN]: org.apache.commons.lang.UnhandledException: Plugin SternalBoard v2.1.0 generated an exception while executing task 53 [22:57:14] [WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(SourceFile:57) [22:57:14] [WARN]: at org.github.paperspigot.ServerSchedulerReportingWrapper.run(SourceFile:22) [22:57:14] [WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [22:57:14] [WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [22:57:14] [WARN]: at java.lang.Thread.run(Unknown Source) [22:57:14] [WARN]: Caused by: java.lang.RuntimeException: Unable to update SternalBoard lines [22:57:14] [WARN]: at com.xism4.sternalboard.SternalBoardHandler.updateLine(SternalBoardHandler.java:272) [22:57:14] [WARN]: at com.xism4.sternalboard.managers.animation.tasks.LineUpdateTask.run(LineUpdateTask.java:38) [22:57:14] [WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(SourceFile:59) [22:57:14] [WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(SourceFile:53) [22:57:14] [WARN]: ... 4 more [22:57:14] [WARN]: Caused by: java.lang.IllegalStateException: This SternalBoard is deleted [22:57:14] [WARN]: at com.xism4.sternalboard.SternalBoardHandler.sendPacket(SternalBoardHandler.java:566) [22:57:14] [WARN]: at com.xism4.sternalboard.SternalBoardHandler.sendTeamPacket(SternalBoardHandler.java:561) [22:57:14] [WARN]: at com.xism4.sternalboard.SternalBoardHandler.updateLine(SternalBoardHandler.java:256) [22:57:14] [WARN]: ... 7 more

Fixed on 2.2.1, i will close this
