### ISSUE TITLE
SternalBoard not shown (IllegalArgumentException)

### ISSUE THREAD

**Issue by skyface753** [ShieldCommunity/SternalBoard#50]
I get the following error, when a user connects to the server. I didn't found any other logs, that enclose the error. 
The Board isn't shown.

However while booting the server or reloading the SternalBoard config, no error occurs.

The Placeholder Api is also the newest Version.

````
Caused by: java.lang.IllegalArgumentException: Attempt to get net.minecraft.server.level.PlayerInteractManager field "net.minecraft.server.level.EntityPlayer.e" with illegal data type conversion to int
	at jdk.internal.reflect.FieldAccessorImpl.newGetIllegalArgumentException(Unknown Source) ~[?:?]
	at jdk.internal.reflect.FieldAccessorImpl.newGetIntIllegalArgumentException(Unknown Source) ~[?:?]
	at jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.getInt(Unknown Source) ~[?:?]
	at java.lang.reflect.Field.getInt(Unknown Source) ~[?:?]
	at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:66) ~[?:?]
	at com.extendedclip.papi.expansion.player.PlayerUtil$1.apply(PlayerUtil.java:50) ~[?:?]
	at com.extendedclip.papi.expansion.player.PlayerUtil.getPing(PlayerUtil.java:122) ~[?:?]
	at com.extendedclip.papi.expansion.player.PlayerExpansion.retrievePing(PlayerExpansion.java:481) ~[?:?]
	at com.extendedclip.papi.expansion.player.PlayerExpansion.onRequest(PlayerExpansion.java:403) ~[?:?]
	at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) ~[PlaceholderAPI-2.11.3.jar:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71) ~[PlaceholderAPI-2.11.3.jar:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99) ~[PlaceholderAPI-2.11.3.jar:?]
	at com.xism4.sternalboard.utils.TextUtils.processPlaceholders(TextUtils.java:63) ~[SternalBoard-2.2.0.jar:?]
	at com.xism4.sternalboard.Scoreboards.lambda$updateFromSection$0(Scoreboards.java:28) ~[SternalBoard-2.2.0.jar:?]
	at java.util.ArrayList.replaceAllRange(Unknown Source) ~[?:?]
	at java.util.ArrayList.replaceAll(Unknown Source) ~[?:?]
	at com.xism4.sternalboard.Scoreboards.updateFromSection(Scoreboards.java:28) ~[SternalBoard-2.2.0.jar:?]
	at com.xism4.sternalboard.managers.ScoreboardManager.setScoreboard(ScoreboardManager.java:80) ~[SternalBoard-2.2.0.jar:?]
	at com.xism4.sternalboard.managers.ScoreboardManager.toggle(ScoreboardManager.java:110) ~[SternalBoard-2.2.0.jar:?]
	at com.xism4.sternalboard.commands.SternalCommand.toggleSubcommand(SternalCommand.java:81) ~[SternalBoard-2.2.0.jar:?]
	at com.xism4.sternalboard.commands.SternalCommand.onCommand(SternalCommand.java:42) ~[SternalBoard-2.2.0.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	... 23 more
```

**Comment by skyface753** [comment]
It was an error with the PlaceholderAPI Cache, my bad.
